import { Roboto } from 'next/font/google'
import './globals.css'
import Header from '@/components/layout/Header.js'

const roboto = Roboto({ subsets: ['latin'] , weight: ['400', '500', '700']})

export const metadata = {
  title: 'UTD Parking Spotter',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className= "bg-background" >
        <main className="max-w-4xl mx-auto p-4">
          <Header/>
          {children}
          <footer class="border-t p-8 text-center text-gray-500 mt-16">
            @2023 All rights reserved
          </footer>
        </main>
      </body>
    </html>
  )
}
